name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Lines
          plugin_lines: yes
          # Traffic
          plugin_traffic: yes
          # Habits
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_charts: yes
          # Followup
          plugin_followup: yes
          # Topics
          #plugin_topics: yes
          #plugin_topics_sort: stars
          #plugin_topics_mode: mastered
          #plugin_topics_limit: 0
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 8
          # Iso Calendar
          plugin_isocalendar: yes
          # Self skip
          plugin_selfskip: yes
          # Anilist
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_user: lgou2w
          plugin_anilist_limit_characters: 22
